# Generated by Django 5.2.7 on 2025-11-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_sale_product_same_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='same_price',
            new_name='sale_price',
        ),
    ]
